### ISSUE TITLE
Error finding configuration file

### ISSUE THREAD

**Issue by aharris88** [BibleJS/BibleApp#12]
I just installed with `npm install -g bible` and when I run `bible`, I get the following error:

```
warn  [10:10.51 - 09.07.2015] No configuration file was found. Initing the configuration file.
fs.js:502
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: ENOENT, no such file or directory 'undefined/.bible-config.json'
    at Error (native)
    at Object.fs.openSync (fs.js:502:18)
    at Object.fs.writeFileSync (fs.js:1103:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/bible/bible.js:43:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

Even if I create the configuration file by hand I still get this error.

**Comment by IonicaBizau** [comment]
Thanks for the heads-up! Indeed, we have to update the dependencies.

**Comment by IonicaBizau** [comment]
Hopefully, this is now fixed! Install it using `npm i -g bible@latest`. :tada:

**Comment by aharris88** [comment]
That works! Thanks for the quick work.

**Comment by IonicaBizau** [comment]
@aharris88 You're welcome! I noticed that error but waited for the first guy to report it. :smile:
