### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by grymmjack** [BibleJS/BibleApp#27]
Hi,

Bummed I cannot use this. I was looking forward to it.

Could you please help?

Thanks!
```
gj@DESKTOP-MH9OVO5:~/.bible/en$ bible --lang en 'John 3:16'
Reference: John 3:16
/usr/local/lib/node_modules/bible/node_modules/bible.js/lib/index.js:97
                    for (var i = 0; i < verses.length; ++i) {
                                               ^

TypeError: Cannot read property 'length' of undefined
    at /usr/local/lib/node_modules/bible/node_modules/bible.js/lib/index.js:97:48
    at request (/home/gj/.bible/en/lib/index.js:22:24)
    at maybeCallback (/home/gj/.bible/en/node_modules/jsonrequest/lib/index.js:57:24)
    at Function.<anonymous> (/home/gj/.bible/en/node_modules/tinyreq/lib/index.js:58:9)
    at res (/home/gj/.bible/en/node_modules/assured/lib/index.js:27:12)
    at IncomingMessage.<anonymous> (/home/gj/.bible/en/node_modules/tinyreq/lib/index.js:101:13)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

**Comment by timsayshey** [comment]
Same here

**Comment by timsayshey** [comment]
@grymmjack Did you ever get it working?

**Comment by grymmjack** [comment]
no :(

**Comment by menporulporiayalan** [comment]
Is it get fixed?

**Comment by Ivl-Nunez** [comment]
> Is it get fixed?

Don't think so. I'm having the same issue. Not sure if I have the skill to fix, but will attempt.

**Comment by marlocarlo** [comment]
Looks like a promising app but simply doesn't work!!

**Comment by grymmjack** [comment]
I can help too, @Ivl-Nunez if you would like a peer. 

I know JS pretty well (browser based, DOM, etc.), but I don't know the node stuff as much. Reach out if you would like to team up to try and fix. 

We can prioritize our work for the Lord.

**Comment by IonicaBizau** [comment]
I am on it. It is an issue that appeared after modifying the reference format.

**Comment by IonicaBizau** [comment]
The easiest way to get the fix is:

```sh
rm -rf ~/.bible
bible --lang en 'John 3:16'
```

**Comment by Ivl-Nunez** [comment]
Thanks, working great now!
